In [8]:
import numpy as np
from sklearn.metrics import DistanceMetric
dist = DistanceMetric.get_metric('euclidean')
X = [[0,1], [2, 1], [-1, 2]]
Y = [[2, 3], [2, 0.5]]
dist.pairwise(X,Y)

array([[2.82842712, 2.06155281],
       [2.        , 0.5       ],
       [3.16227766, 3.35410197]])

In [2]:
dist = DistanceMetric.get_metric('manhattan')
X = [[1, 2], [3, 4], [5, 6]]
Y = [[7, 8], [9, 10]]
dist.pairwise(X,Y)

array([[12., 16.],
       [ 8., 12.],
       [ 4.,  8.]])

In [14]:
dist = DistanceMetric.get_metric('euclidean')
X = [[4,4]]
Y = [[4, 0]]
dist.pairwise(X,Y)

array([[4.]])

In [12]:
x = [3, 5, 4]
y = [0, 1, 6]
center = sum(x)/len(x), sum(y)/len(y)
center

(4.0, 2.3333333333333335)

In [15]:
centroids = [[1,1], [2,1], [2,-1]]
points =  [[1,2]]
dist = DistanceMetric.get_metric('euclidean')
dist.pairwise(X,Y)

array([[4.]])